export function WebGLLights(extensions: any): {
    setup: (lights: any) => void;
    setupView: (lights: any, camera: any) => void;
    state: {
        version: number;
        hash: {
            directionalLength: number;
            pointLength: number;
            spotLength: number;
            rectAreaLength: number;
            hemiLength: number;
            numDirectionalShadows: number;
            numPointShadows: number;
            numSpotShadows: number;
            numSpotMaps: number;
            numLightProbes: number;
        };
        ambient: number[];
        probe: never[];
        directional: never[];
        directionalShadow: never[];
        directionalShadowMap: never[];
        directionalShadowMatrix: never[];
        spot: never[];
        spotLightMap: never[];
        spotShadow: never[];
        spotShadowMap: never[];
        spotLightMatrix: never[];
        rectArea: never[];
        rectAreaLTC1: null;
        rectAreaLTC2: null;
        point: never[];
        pointShadow: never[];
        pointShadowMap: never[];
        pointShadowMatrix: never[];
        hemi: never[];
        numSpotLightShadowsWithMaps: number;
        numLightProbes: number;
    };
};
