export function WebGLPrograms(renderer: any, environments: any, extensions: any, capabilities: any, bindingStates: any, clipping: any): {
    getParameters: (material: any, lights: any, shadows: any, scene: any, object: any, lightProbeGrids: any) => {
        shaderID: any;
        shaderType: any;
        shaderName: any;
        vertexShader: any;
        fragmentShader: any;
        defines: any;
        customVertexShaderID: any;
        customFragmentShaderID: any;
        isRawShaderMaterial: boolean;
        glslVersion: any;
        precision: any;
        batching: boolean;
        batchingColor: boolean;
        instancing: boolean;
        instancingColor: boolean;
        instancingMorph: boolean;
        outputColorSpace: any;
        alphaToCoverage: boolean;
        map: boolean;
        matcap: boolean;
        envMap: boolean;
        envMapMode: any;
        envMapCubeUVHeight: any;
        aoMap: boolean;
        lightMap: boolean;
        bumpMap: boolean;
        normalMap: boolean;
        displacementMap: boolean;
        emissiveMap: boolean;
        normalMapObjectSpace: boolean;
        normalMapTangentSpace: boolean;
        packedNormalMap: boolean;
        metalnessMap: boolean;
        roughnessMap: boolean;
        anisotropy: boolean;
        anisotropyMap: boolean;
        clearcoat: boolean;
        clearcoatMap: boolean;
        clearcoatNormalMap: boolean;
        clearcoatRoughnessMap: boolean;
        dispersion: boolean;
        iridescence: boolean;
        iridescenceMap: boolean;
        iridescenceThicknessMap: boolean;
        sheen: boolean;
        sheenColorMap: boolean;
        sheenRoughnessMap: boolean;
        specularMap: boolean;
        specularColorMap: boolean;
        specularIntensityMap: boolean;
        transmission: boolean;
        transmissionMap: boolean;
        thicknessMap: boolean;
        gradientMap: boolean;
        opaque: boolean;
        alphaMap: boolean;
        alphaTest: boolean;
        alphaHash: boolean;
        combine: any;
        mapUv: string | false;
        aoMapUv: string | false;
        lightMapUv: string | false;
        bumpMapUv: string | false;
        normalMapUv: string | false;
        displacementMapUv: string | false;
        emissiveMapUv: string | false;
        metalnessMapUv: string | false;
        roughnessMapUv: string | false;
        anisotropyMapUv: string | false;
        clearcoatMapUv: string | false;
        clearcoatNormalMapUv: string | false;
        clearcoatRoughnessMapUv: string | false;
        iridescenceMapUv: string | false;
        iridescenceThicknessMapUv: string | false;
        sheenColorMapUv: string | false;
        sheenRoughnessMapUv: string | false;
        specularMapUv: string | false;
        specularColorMapUv: string | false;
        specularIntensityMapUv: string | false;
        transmissionMapUv: string | false;
        thicknessMapUv: string | false;
        alphaMapUv: string | false;
        vertexTangents: boolean;
        vertexNormals: boolean;
        vertexColors: any;
        vertexAlphas: boolean;
        pointsUvs: boolean;
        fog: boolean;
        useFog: boolean;
        fogExp2: any;
        flatShading: any;
        sizeAttenuation: boolean;
        logarithmicDepthBuffer: any;
        reversedDepthBuffer: any;
        skinning: boolean;
        hasPositionAttribute: boolean;
        morphTargets: boolean;
        morphNormals: boolean;
        morphColors: boolean;
        morphTargetsCount: any;
        morphTextureStride: number;
        numDirLights: any;
        numPointLights: any;
        numSpotLights: any;
        numSpotLightMaps: any;
        numRectAreaLights: any;
        numHemiLights: any;
        numDirLightShadows: any;
        numPointLightShadows: any;
        numSpotLightShadows: any;
        numSpotLightShadowsWithMaps: any;
        numLightProbes: any;
        numLightProbeGrids: any;
        numClippingPlanes: any;
        numClipIntersection: any;
        dithering: any;
        shadowMapEnabled: any;
        shadowMapType: any;
        toneMapping: number;
        decodeVideoTexture: boolean;
        decodeVideoTextureEmissive: boolean;
        premultipliedAlpha: any;
        doubleSided: boolean;
        flipSided: boolean;
        useDepthPacking: boolean;
        depthPacking: any;
        index0AttributeName: any;
        extensionClipCullDistance: any;
        extensionMultiDraw: any;
        rendererExtensionParallelShaderCompile: any;
        customProgramCacheKey: any;
    };
    getProgramCacheKey: (parameters: any) => string;
    getUniforms: (material: any) => any;
    acquireProgram: (parameters: any, cacheKey: any) => any;
    releaseProgram: (program: any) => void;
    releaseShaderCache: (material: any) => void;
    programs: any[];
    dispose: () => void;
};
