export function WebGLState(gl: any, extensions: any): {
    buffers: {
        color: any;
        depth: any;
        stencil: any;
    };
    enable: (id: any) => void;
    disable: (id: any) => void;
    bindFramebuffer: (target: any, framebuffer: any) => boolean;
    drawBuffers: (renderTarget: any, framebuffer: any) => void;
    useProgram: (program: any) => boolean;
    setBlending: (blending: any, blendEquation: any, blendSrc: any, blendDst: any, blendEquationAlpha: any, blendSrcAlpha: any, blendDstAlpha: any, blendColor: any, blendAlpha: any, premultipliedAlpha: any) => void;
    setMaterial: (material: any, frontFaceCW: any) => void;
    setFlipSided: (flipSided: any) => void;
    setCullFace: (cullFace: any) => void;
    setLineWidth: (width: any) => void;
    setPolygonOffset: (polygonOffset: any, factor: any, units: any) => void;
    setScissorTest: (scissorTest: any) => void;
    activeTexture: (webglSlot: any) => void;
    bindTexture: (webglType: any, webglTexture: any, webglSlot: any) => void;
    unbindTexture: () => void;
    compressedTexImage2D: (...args: any[]) => void;
    compressedTexImage3D: (...args: any[]) => void;
    texImage2D: (...args: any[]) => void;
    texImage3D: (...args: any[]) => void;
    pixelStorei: (name: any, value: any) => void;
    getParameter: (name: any) => any;
    updateUBOMapping: (uniformsGroup: any, program: any) => void;
    uniformBlockBinding: (uniformsGroup: any, program: any) => void;
    texStorage2D: (...args: any[]) => void;
    texStorage3D: (...args: any[]) => void;
    texSubImage2D: (...args: any[]) => void;
    texSubImage3D: (...args: any[]) => void;
    compressedTexSubImage2D: (...args: any[]) => void;
    compressedTexSubImage3D: (...args: any[]) => void;
    scissor: (scissor: any) => void;
    viewport: (viewport: any) => void;
    reset: () => void;
};
