export function blendBurn(...params: any[]): any;
export namespace blendBurn { }
export function blendBurn(...params: any[]): any;
export namespace blendBurn { }
export function blendBurn(...params: any[]): any;
export namespace blendBurn { }
export function blendBurn(...params: any[]): any;
export namespace blendBurn { }
export function blendBurn(...params: any[]): any;
export namespace blendBurn { }
export function blendBurn(...params: any[]): any;
export namespace blendBurn { }
export function blendBurn(...params: any[]): any;
export namespace blendBurn { }
export function burn(...params: any[]): Function;
export function dodge(...params: any[]): Function;
export function screen(...params: any[]): Function;
export function overlay(...params: any[]): Function;
