/**
 * Utility class for LDraw models.
 *
 * @three_import import { LDrawUtils } from 'three/addons/utils/LDrawUtils.js';
 */
export class LDrawUtils {
    /**
     * Merges geometries in the given object by materials and returns a new group object.
     * Use on not indexed geometries. The object buffers reference the old object ones.
     * Special treatment is done to the conditional lines generated by LDrawLoader.
     *
     * @param {Object3D} object - The object to merge.
     * @returns {Group} The merged object.
     */
    static mergeObject(object: Object3D): Group;
}
import { Group } from 'three';
