export class Profiler extends EventDispatcher {
    constructor(inspector: any);
    inspector: any;
    tabs: {};
    activeTabId: any;
    isResizing: boolean;
    lastHeightBottom: number;
    lastWidthRight: number;
    position: string;
    detachedWindows: any[];
    maxZIndex: number;
    nextTabOriginalIndex: number;
    getSize(): {
        width: number;
        height: number;
    };
    get isMobile(): boolean;
    get isSmallScreen(): boolean;
    detectMobile(): boolean;
    setupOrientationListener(): void;
    setupWindowResizeListener(): void;
    constrainWindowToBounds(windowPanel: any): void;
    setupShell(): void;
    domElement: HTMLDivElement | undefined;
    toggleButton: HTMLButtonElement | undefined;
    builtinTabsContainer: Element | null | undefined;
    miniPanel: HTMLDivElement | undefined;
    panel: HTMLDivElement | undefined;
    tabsContainer: HTMLDivElement | undefined;
    floatingBtn: HTMLButtonElement | undefined;
    maximizeBtn: HTMLButtonElement | undefined;
    contentWrapper: HTMLDivElement | undefined;
    toggleGraph: Graph | undefined;
    setupResizing(): void;
    toggleMaximize(): void;
    hide(): void;
    show(tab: any): void;
    addTab(tab: any): void;
    addBuiltinTab(tab: any): void;
    removeTab(tab: any): void;
    updatePanelSize(): void;
    checkHeaderScroll(): void;
    setupTabDragAndDrop(tab: any): void;
    createPreviewWindow(tab: any, x: any, y: any): HTMLDivElement;
    detachTab(tab: any, x: any, y: any): void;
    createDetachedWindow(tab: any, x: any, y: any): {
        panel: HTMLDivElement;
        tab: any;
    };
    bringWindowToFront(windowPanel: any): void;
    setupDetachedWindowDrag(windowPanel: any, header: any, tab: any): void;
    setupDetachedWindowResize(windowPanel: any, resizerTop: any, resizerRight: any, resizerBottom: any, resizerLeft: any, resizerCorner: any): void;
    reattachTab(tab: any): void;
    setActiveTab(id: any): void;
    togglePanel(): void;
    togglePosition(): void;
    setPosition(targetPosition: any): void;
    saveLayout(): void;
    loadLayout(): void;
    isLoadingLayout: boolean | undefined;
    pendingDetachedTabs: any;
    restoreDetachedTabs(): void;
}
import { EventDispatcher } from 'three';
import { Graph } from './Graph.js';
