export function mx_aastep(threshold: any, value: any): any;
export function mx_ramplr(valuel: any, valuer: any, texcoord?: AttributeNode<vec2>): any;
export function mx_ramptb(valuet: any, valueb: any, texcoord?: AttributeNode<vec2>): any;
export function mx_ramp4(valuetl: any, valuetr: any, valuebl: any, valuebr: any, texcoord?: AttributeNode<vec2>): any;
export function mx_splitlr(valuel: any, valuer: any, center: any, texcoord?: AttributeNode<vec2>): any;
export function mx_splittb(valuet: any, valueb: any, center: any, texcoord?: AttributeNode<vec2>): any;
export function mx_transform_uv(uv_scale?: number, uv_offset?: number, uv_geo?: AttributeNode<vec2>): any;
export function mx_safepower(in1: any, in2?: number): any;
export function mx_contrast(input: any, amount?: number, pivot?: number): any;
export function mx_noise_float(texcoord?: AttributeNode<vec2>, amplitude?: number, pivot?: number): any;
export function mx_noise_vec3(texcoord?: AttributeNode<vec2>, amplitude?: number, pivot?: number): any;
export function mx_noise_vec4(texcoord?: AttributeNode<vec2>, amplitude?: number, pivot?: number): any;
export function mx_unifiednoise2d(noiseType: any, texcoord?: AttributeNode<vec2>, freq?: any, offset?: any, jitter?: number, outmin?: number, outmax?: number, clampoutput?: boolean, octaves?: number, lacunarity?: number, diminish?: number): any;
export function mx_unifiednoise3d(noiseType: any, texcoord?: AttributeNode<vec2>, freq?: any, offset?: any, jitter?: number, outmin?: number, outmax?: number, clampoutput?: boolean, octaves?: number, lacunarity?: number, diminish?: number): any;
export function mx_worley_noise_float(texcoord?: AttributeNode<vec2>, jitter?: number): any;
export function mx_worley_noise_vec2(texcoord?: AttributeNode<vec2>, jitter?: number): any;
export function mx_worley_noise_vec3(texcoord?: AttributeNode<vec2>, jitter?: number): any;
export function mx_cell_noise_float(texcoord?: AttributeNode<vec2>): any;
export function mx_fractal_noise_float(position?: AttributeNode<vec2>, octaves?: number, lacunarity?: number, diminish?: number, amplitude?: number): any;
export function mx_fractal_noise_vec2(position?: AttributeNode<vec2>, octaves?: number, lacunarity?: number, diminish?: number, amplitude?: number): any;
export function mx_fractal_noise_vec3(position?: AttributeNode<vec2>, octaves?: number, lacunarity?: number, diminish?: number, amplitude?: number): any;
export function mx_fractal_noise_vec4(position?: AttributeNode<vec2>, octaves?: number, lacunarity?: number, diminish?: number, amplitude?: number): any;
export function mx_add(in1: any, in2?: any): any;
export function mx_subtract(in1: any, in2?: any): any;
export function mx_multiply(in1: any, in2?: any): any;
export function mx_divide(in1: any, in2?: any): any;
export function mx_modulo(in1: any, in2?: any): any;
export function mx_power(in1: any, in2?: any): any;
export function mx_atan2(in1?: any, in2?: any): any;
export function mx_timer(): UniformNode<float>;
export function mx_frame(): UniformNode<uint>;
export function mx_invert(in1: any, amount?: any): any;
export function mx_ifgreater(value1: any, value2: any, in1: any, in2: any): any;
export function mx_ifgreatereq(value1: any, value2: any, in1: any, in2: any): any;
export function mx_ifequal(value1: any, value2: any, in1: any, in2: any): any;
export function mx_separate(in1: any, channelOrOut?: null): any;
export function mx_place2d(texcoord: any, pivot?: any, scale?: any, rotate?: any, offset?: any): any;
export function mx_rotate2d(input: any, amount: any): any;
export function mx_rotate3d(input: any, amount: any, axis: any): any;
export function mx_heighttonormal(input: any, scale: any): any;
import { mx_hsvtorgb } from './lib/mx_hsv.js';
import { mx_rgbtohsv } from './lib/mx_hsv.js';
import { mx_srgb_texture_to_lin_rec709 } from './lib/mx_transform_color.js';
export { mx_hsvtorgb, mx_rgbtohsv, mx_srgb_texture_to_lin_rec709 };
