export default TSLGraphEditor;
declare class TSLGraphEditor extends Extension {
    constructor(options?: {});
    autoGraphId: boolean;
    iframe: HTMLIFrameElement;
    editorOrigin: string;
    material: any;
    uniforms: any;
    isReady: boolean;
    _codeData: any;
    _codeSaveTimeout: number | null;
    _pending: Map<any, any>;
    _resolveReady: ((value: any) => void) | null;
    _editorReady: Promise<any>;
    get hasGraphs(): boolean;
    _initPicker(inspector: any): void;
    apply(scene: any): this;
    restoreMaterial(material: any): void;
    init(inspector: any): void;
    setMaterial(material: any): Promise<void>;
    loadGraph(graphData: any): Promise<void>;
    command(type: any, payload: any): Promise<any>;
    getCode(): Promise<any>;
    getTSLFunction(): Promise<any>;
    getGraph(): Promise<any>;
    onResponse(): Promise<void>;
    onEvent(type: any, payload: any): Promise<void>;
    onMessage(event: any): Promise<void>;
    _setMaterial(material: any): Promise<void>;
    materialDefault: any;
    _getGraphType(material: any): "material/physical" | "material/standard" | "material/phong" | "material/basic" | "material/sprite" | "material/node";
    _showManagerModal(): void;
    _exportData(): void;
    _importData(): void;
    getCodes(): any;
    _saveCode(): void;
    _restoreMaterial(): void;
    _updateMaterial(): Promise<void>;
    _updateUniforms(uniforms: any): void;
    _isEditorMessage(value: any): boolean;
    _makeRequestId(): string;
    _post(message: any): void;
}
import { Extension } from 'three/addons/inspector/Extension.js';
