import * as fs from 'node:fs';
import * as path from 'node:path';
import { argv } from 'node:process';

const files = [
    'examples/jsm/csm/CSMFrustum',
    'examples/jsm/geometries/LoftGeometry',
    'examples/jsm/lighting/ClusteredLighting',
    'examples/jsm/lighting/LightProbeGrid',
    'examples/jsm/misc/TileCreasedNormalsPlugin',
    'examples/jsm/tsl/lighting/ClusteredLightsNode',
    'examples/jsm/tsl/math/curlNoise',
    'examples/jsm/tsl/utils/GroundedSkybox',
    'examples/jsm/webxr/WebGLXRFallback',
    'src/animation/tracks/BooleanKeyframeTrack',
    'src/animation/tracks/ColorKeyframeTrack',
    'src/animation/tracks/NumberKeyframeTrack',
    'src/animation/tracks/QuaternionKeyframeTrack',
    'src/animation/tracks/StringKeyframeTrack',
    'src/animation/tracks/VectorKeyframeTrack',
    'src/animation/AnimationAction',
    'src/animation/AnimationClip',
    'src/animation/AnimationMixer',
    'src/animation/AnimationObjectGroup',
    'src/animation/AnimationUtils',
    'src/animation/KeyframeTrack',
    'src/animation/PropertyBinding',
    'src/animation/PropertyMixer',
    'src/audio/Audio',
    'src/audio/AudioAnalyser',
    'src/audio/AudioContext',
    'src/audio/AudioListener',
    'src/audio/PositionalAudio',
    'src/cameras/ArrayCamera',
    'src/cameras/Camera',
    'src/cameras/CubeCamera',
    'src/cameras/OrthographicCamera',
    'src/cameras/PerspectiveCamera',
    'src/cameras/StereoCamera',
    'src/extras/core/ShapePath',
    'src/helpers/ArrowHelper',
    'src/helpers/AxesHelper',
    'src/helpers/Box3Helper',
    'src/helpers/BoxHelper',
    'src/helpers/CameraHelper',
    'src/helpers/DirectionalLightHelper',
    'src/helpers/GridHelper',
    'src/helpers/HemisphereLightHelper',
    'src/helpers/PlaneHelper',
    'src/helpers/PointLightHelper',
    'src/helpers/PolarGridHelper',
    'src/helpers/SkeletonHelper',
    'src/helpers/SpotLightHelper',
    'src/lights/webgpu/IESSpotLight',
    'src/lights/webgpu/ProjectorLight',
    'src/lights/AmbientLight',
    'src/lights/DirectionalLight',
    'src/lights/DirectionalLightShadow',
    'src/lights/HemisphereLight',
    'src/lights/Light',
    'src/lights/LightProbe',
    'src/lights/LightShadow',
    'src/lights/PointLight',
    'src/lights/PointLightShadow',
    'src/lights/RectAreaLight',
    'src/lights/SpotLight',
    'src/lights/SpotLightShadow',
    'src/materials/nodes/manager/NodeMaterialObserver',
    'src/materials/nodes/Line2NodeMaterial',
    'src/materials/nodes/LineBasicNodeMaterial',
    'src/materials/nodes/LineDashedNodeMaterial',
    'src/materials/nodes/MeshBasicNodeMaterial',
    'src/materials/nodes/MeshLambertNodeMaterial',
    'src/materials/nodes/MeshMatcapNodeMaterial',
    'src/materials/nodes/MeshNormalNodeMaterial',
    'src/materials/nodes/MeshPhongNodeMaterial',
    'src/materials/nodes/MeshPhysicalNodeMaterial',
    'src/materials/nodes/MeshSSSNodeMaterial',
    'src/materials/nodes/MeshStandardNodeMaterial',
    'src/materials/nodes/MeshToonNodeMaterial',
    'src/materials/nodes/NodeMaterial',
    'src/materials/nodes/NodeMaterials',
    'src/materials/nodes/PointsNodeMaterial',
    'src/materials/nodes/ShadowNodeMaterial',
    'src/materials/nodes/SpriteNodeMaterial',
    'src/materials/nodes/VolumeNodeMaterial',
    'src/materials/LineBasicMaterial',
    'src/materials/LineDashedMaterial',
    'src/materials/Material',
    'src/materials/Materials',
    'src/materials/MeshBasicMaterial',
    'src/materials/MeshDepthMaterial',
    'src/materials/MeshDistanceMaterial',
    'src/materials/MeshLambertMaterial',
    'src/materials/MeshMatcapMaterial',
    'src/materials/MeshNormalMaterial',
    'src/materials/MeshPhongMaterial',
    'src/materials/MeshPhysicalMaterial',
    'src/materials/MeshStandardMaterial',
    'src/materials/MeshToonMaterial',
    'src/materials/PointsMaterial',
    'src/materials/RawShaderMaterial',
    'src/materials/ShaderMaterial',
    'src/materials/ShadowMaterial',
    'src/materials/SpriteMaterial',
    'src/math/Box3',
    'src/math/FrustumArray',
    'src/math/interpolants/BezierInterpolant',
    'src/math/interpolants/CubicInterpolant',
    'src/math/interpolants/DiscreteInterpolant',
    'src/math/interpolants/LinearInterpolant',
    'src/math/interpolants/QuaternionLinearInterpolant',
    'src/math/Interpolant',
    'src/math/Matrix4',
    'src/nodes/accessors/Batch',
    'src/nodes/accessors/BufferAttributeNode',
    'src/nodes/accessors/Instance',
    'src/nodes/accessors/Morph',
    'src/nodes/accessors/Skinning',
    'src/nodes/core/constants',
    'src/nodes/core/Node',
    'src/nodes/core/NodeAttribute',
    'src/nodes/core/NodeCache',
    'src/nodes/core/NodeParser',
    'src/nodes/core/NodeUniform',
    'src/nodes/core/NodeVar',
    'src/nodes/core/NodeVarying',
    'src/nodes/core/OverrideContextNode',
    'src/nodes/core/StructType',
    'src/nodes/core/StructTypeNode',
    'src/nodes/core/UniformNode',
    'src/nodes/display/BlendModes',
    'src/nodes/display/FrontFacingNode',
    'src/nodes/display/PremultiplyAlphaFunctions',
    'src/nodes/utils/EquirectUV',
    'src/nodes/utils/Packing',
    'src/renderers/common/BufferUtils',
    'src/renderers/common/BundleGroup',
    'src/renderers/common/CanvasTarget',
    'src/renderers/common/ClippingContext',
    'src/renderers/common/Constants',
    'src/renderers/common/CubeRenderTarget',
    'src/renderers/common/Info',
    'src/renderers/common/InspectorBase',
    'src/renderers/common/Lighting',
    'src/renderers/common/ReadbackBuffer',
    'src/renderers/common/Renderer',
    'src/renderers/common/TimestampQueryPool',
    'src/renderers/common/XRManager',
    'src/renderers/webgl-fallback/utils/WebGLCapabilities',
    'src/renderers/webgpu/nodes/BasicNodeLibrary',
    'src/renderers/webgpu/nodes/StandardNodeLibrary',
    'src/scenes/Fog',
    'src/scenes/FogExp2',
    'src/scenes/Scene',
];

const inDir = './jsdoc';
const outDir = '../types/three';

for (const file of files) {
    console.log(file);
    const fileContents = fs.readFileSync(path.join(inDir, `${file}.d.ts`), { encoding: 'utf-8' });
    const outFile = path.join(outDir, `${file}.d.ts`);
    if (argv[2] === 'copy') {
        fs.mkdirSync(path.dirname(outFile), { recursive: true });
        fs.writeFileSync(outFile, fileContents);
    } else if (argv[2] === 'check') {
        const outFileContents = fs.readFileSync(outFile, { encoding: 'utf-8' });
        if (fileContents !== outFileContents) {
            throw new Error(`The built declaration file for ${file} differs.`);
        }
    } else {
        throw new Error('Expected program argument.');
    }
}
