import * as fs from 'node:fs';
import * as path from 'node:path';
import { argv } from 'node:process';

const files = [
    'animation/tracks/BooleanKeyframeTrack',
    'animation/tracks/ColorKeyframeTrack',
    'animation/tracks/NumberKeyframeTrack',
    'animation/tracks/QuaternionKeyframeTrack',
    'animation/tracks/StringKeyframeTrack',
    'animation/tracks/VectorKeyframeTrack',
    'animation/AnimationAction',
    'animation/AnimationClip',
    'animation/AnimationMixer',
    'animation/AnimationObjectGroup',
    'animation/AnimationUtils',
    'animation/KeyframeTrack',
    'animation/PropertyBinding',
    'animation/PropertyMixer',
    'audio/Audio',
    'audio/AudioAnalyser',
    'audio/AudioContext',
    'audio/AudioListener',
    'audio/PositionalAudio',
    'cameras/ArrayCamera',
    'cameras/Camera',
    'cameras/CubeCamera',
    'cameras/OrthographicCamera',
    'cameras/PerspectiveCamera',
    'cameras/StereoCamera',
    'helpers/ArrowHelper',
    'helpers/AxesHelper',
    'helpers/Box3Helper',
    'helpers/BoxHelper',
    'helpers/CameraHelper',
    'helpers/DirectionalLightHelper',
    'helpers/GridHelper',
    'helpers/HemisphereLightHelper',
    'helpers/PlaneHelper',
    'helpers/PointLightHelper',
    'helpers/PolarGridHelper',
    'helpers/SkeletonHelper',
    'helpers/SpotLightHelper',
    'lights/webgpu/IESSpotLight',
    'lights/webgpu/ProjectorLight',
    'lights/AmbientLight',
    'lights/DirectionalLight',
    'lights/DirectionalLightShadow',
    'lights/HemisphereLight',
    'lights/Light',
    'lights/LightProbe',
    'lights/LightShadow',
    'lights/PointLight',
    'lights/PointLightShadow',
    'lights/RectAreaLight',
    'lights/SpotLight',
    'lights/SpotLightShadow',
    'materials/nodes/manager/NodeMaterialObserver',
    'materials/nodes/Line2NodeMaterial',
    'materials/nodes/LineBasicNodeMaterial',
    'materials/nodes/LineDashedNodeMaterial',
    'materials/nodes/MeshBasicNodeMaterial',
    'materials/nodes/MeshLambertNodeMaterial',
    'materials/nodes/MeshMatcapNodeMaterial',
    'materials/nodes/MeshNormalNodeMaterial',
    'materials/nodes/MeshPhongNodeMaterial',
    'materials/nodes/MeshPhysicalNodeMaterial',
    'materials/nodes/MeshSSSNodeMaterial',
    'materials/nodes/MeshStandardNodeMaterial',
    'materials/nodes/MeshToonNodeMaterial',
    'materials/nodes/NodeMaterial',
    'materials/nodes/NodeMaterials',
    'materials/nodes/PointsNodeMaterial',
    'materials/nodes/ShadowNodeMaterial',
    'materials/nodes/SpriteNodeMaterial',
    'materials/nodes/VolumeNodeMaterial',
    'materials/LineBasicMaterial',
    'materials/LineDashedMaterial',
    'materials/Material',
    'materials/Materials',
    'materials/MeshBasicMaterial',
    'materials/MeshDepthMaterial',
    'materials/MeshDistanceMaterial',
    'materials/MeshLambertMaterial',
    'materials/MeshMatcapMaterial',
    'materials/MeshNormalMaterial',
    'materials/MeshPhongMaterial',
    'materials/MeshPhysicalMaterial',
    'materials/MeshStandardMaterial',
    'materials/MeshToonMaterial',
    'materials/PointsMaterial',
    'materials/RawShaderMaterial',
    'materials/ShaderMaterial',
    'materials/ShadowMaterial',
    'materials/SpriteMaterial',
    'nodes/accessors/BufferAttributeNode',
    'nodes/core/constants',
    'nodes/core/Node',
    'nodes/core/NodeAttribute',
    'nodes/core/NodeCache',
    'nodes/core/NodeParser',
    'nodes/core/NodeUniform',
    'nodes/core/NodeVar',
    'nodes/core/NodeVarying',
    'nodes/core/StructType',
    'nodes/core/StructTypeNode',
    'nodes/core/UniformNode',
    'renderers/common/nodes/NodeBuilderState',
    'renderers/common/nodes/NodeLibrary',
    'renderers/common/nodes/NodeManager',
    'renderers/common/nodes/NodeUniform',
    'renderers/common/nodes/NodeUniformsGroup',
    'renderers/common/Animation',
    'renderers/common/Attributes',
    'renderers/common/Background',
    'renderers/common/BindGroup',
    'renderers/common/Binding',
    'renderers/common/Bindings',
    'renderers/common/Buffer',
    'renderers/common/BufferUtils',
    'renderers/common/BundleGroup',
    'renderers/common/CanvasTarget',
    'renderers/common/ChainMap',
    'renderers/common/ClippingContext',
    'renderers/common/Color4',
    'renderers/common/ComputePipeline',
    'renderers/common/Constants',
    'renderers/common/CubeRenderTarget',
    'renderers/common/DataMap',
    'renderers/common/Geometries',
    'renderers/common/Info',
    'renderers/common/InspectorBase',
    'renderers/common/Pipeline',
    'renderers/common/Pipelines',
    'renderers/common/ProgrammableStage',
    'renderers/common/RenderBundle',
    'renderers/common/RenderBundles',
    'renderers/common/RenderContext',
    'renderers/common/RenderContexts',
    'renderers/common/Renderer',
    'renderers/common/RenderList',
    'renderers/common/RenderLists',
    'renderers/common/RenderObject',
    'renderers/common/RenderObjectPipeline',
    'renderers/common/RenderObjects',
    'renderers/common/Textures',
    'renderers/common/TimestampQueryPool',
    'renderers/common/Uniform',
    'renderers/common/UniformBuffer',
    'renderers/common/UniformsGroup',
    'renderers/common/XRManager',
    'renderers/common/XRRenderTarget',
    'renderers/webgpu/nodes/BasicNodeLibrary',
    'renderers/webgpu/nodes/StandardNodeLibrary',
    'scenes/Fog',
    'scenes/FogExp2',
    'scenes/Scene',
];

const inDir = './jsdoc';
const outDir = '../types/three/src';

for (const file of files) {
    console.log(file);
    const fileContents = fs.readFileSync(path.join(inDir, `${file}.d.ts`), { encoding: 'utf-8' });
    const outFile = path.join(outDir, `${file}.d.ts`);
    if (argv[2] === 'copy') {
        fs.mkdirSync(path.dirname(outFile), { recursive: true });
        fs.writeFileSync(outFile, fileContents);
    } else if (argv[2] === 'check') {
        const outFileContents = fs.readFileSync(outFile, { encoding: 'utf-8' });
        if (fileContents !== outFileContents) {
            throw new Error(`The built declaration file for ${file} differs.`);
        }
    } else {
        throw new Error('Expected program argument.');
    }
}
