export class Viewer extends Tab {
    constructor(options?: {});
    maximizedByFullscreenButton: boolean;
    nodeList: List;
    itemLibrary: Map<any, any>;
    folderLibrary: Map<any, any>;
    canvasNodes: Map<any, any>;
    currentDataList: any[];
    nodes: Item;
    scrollWrapper: HTMLDivElement;
    fullViewerContainer: HTMLDivElement;
    select: HTMLSelectElement;
    backBtn: HTMLButtonElement;
    activeFullNodeId: any;
    pendingRestoreView: boolean;
    splitActive: boolean;
    splitCanvasData: any;
    splitOverlay: HTMLDivElement | null;
    splitLine: HTMLDivElement | null;
    splitQuad: QuadMesh | null;
    splitMaterial: NodeMaterial | null;
    splitUniforms: {
        splitX: import("three/webgpu").UniformNode;
        viewportWidth: import("three/webgpu").UniformNode;
    } | null;
    splitCanvas: HTMLCanvasElement | null;
    splitCanvasTarget: CanvasTarget | null;
    isDraggingThumbnail: boolean;
    activeSourceCanvas: any;
    activePointerIds: Set<any>;
    getFolder(name: any): any;
    addNodeItem(canvasData: any): any;
    splitFullscreen: boolean | undefined;
    setupEventForwarding(sourceCanvas: any): void;
    forwardEvent(event: any, sourceCanvas: any, targetCanvas: any): void;
    init(inspector: any): void;
    setViewMode(mode: any): void;
    showListView(): void;
    showNodeView(nodeId: any): void;
    startSplitMode(canvasData: any): void;
    splitX: number | undefined;
    stopSplitMode(): void;
    updateSplitButtonsState(): void;
    getCanvasDataByNode(renderer: any, node: any): any;
    update(inspector: any): void;
    saveLastView(): void;
}
import { Tab } from '../ui/Tab.js';
import { List } from '../ui/List.js';
import { Item } from '../ui/Item.js';
import { QuadMesh } from 'three/webgpu';
import { NodeMaterial } from 'three/webgpu';
import { CanvasTarget } from 'three/webgpu';
