export class SculptorMesh {
    _nbVertices: number;
    _nbFaces: number;
    _verticesXYZ: any;
    _normalsXYZ: any;
    _renderNormalsXYZ: any;
    _facesABCD: any;
    _trianglesABC: any;
    _vertRingVert: any[];
    _vertRingFace: any[];
    _vertOnEdge: any;
    _faceNormals: any;
    _faceBoxes: any;
    _faceCenters: any;
    _facePosInLeaf: any;
    _faceLeaf: any[];
    _vertTagFlags: any;
    _vertSculptFlags: any;
    _facesTagFlags: any;
    _octree: OctreeCell | null;
    _leavesToUpdate: any[];
    _topologyVersion: number;
    _tagFlag: number;
    _sculptFlag: number;
    getNbVertices(): number;
    getNbFaces(): number;
    getNbTriangles(): number;
    getVertices(): any;
    getNormals(): any;
    getRenderNormals(): any;
    getFaces(): any;
    getTriangles(): any;
    getVerticesRingVert(): any[];
    getVerticesRingFace(): any[];
    getVerticesOnEdge(): any;
    getVerticesTagFlags(): any;
    getVerticesSculptFlags(): any;
    getFaceNormals(): any;
    getFaceBoxes(): any;
    getFaceCenters(): any;
    getFacePosInLeaf(): any;
    getFaceLeaf(): any[];
    getFacesTagFlags(): any;
    getTopologyVersion(): number;
    getSculptFlag(): number;
    nextTagFlag(): number;
    nextSculptFlag(): number;
    addNbVertice(nb: any): void;
    addNbFace(nb: any): void;
    markTopologyChanged(): void;
    initFromGeometry(geometry: any): void;
    _initTopology(): void;
    _computeRingVertices(iVert: any): void;
    _updateGeometry(iFaces: any, iVerts: any): void;
    _updateFacesAabbAndNormal(iFaces: any): void;
    _updateVerticesNormal(iVerts: any): void;
    _updateOctree(iFaces: any): void;
    _computeOctree(): void;
    _updateOctreeRemove(iFaces: any): Uint32Array<ArrayBuffer>;
    _updateOctreeAdd(iFaces: any): void;
    intersectRay(vNear: any, eyeDir: any): any;
    intersectSphere(center: any, radiusSq: any, collectLeaves?: boolean): any;
    getVerticesFromFaces(iFaces: any): Uint32Array<ArrayBuffer>;
    getFacesFromVertices(iVerts: any): Uint32Array<ArrayBuffer>;
    expandsFaces(iFaces: any, nRing: any): Uint32Array<ArrayBuffer>;
    expandsVertices(iVerts: any, nRing: any): Uint32Array<ArrayBuffer>;
    updateRenderTriangles(iFaces: any): void;
    updateVerticesOnEdge(iVerts: any): void;
    updateTopology(iFaces: any, iVerts: any): void;
    _resizeArray(array: any, requiredLength: any): any;
    reAllocateArrays(nbAddElements: any): void;
    balanceOctree(): void;
}
declare class OctreeCell {
    constructor(parent: any);
    _parent: any;
    _depth: any;
    _children: any[];
    _aabbLoose: number[];
    _aabbSplit: number[];
    _iFaces: any[];
    _queuedForUpdate: boolean;
    resetNbFaces(nbFaces: any): void;
    build(mesh: any): void;
    _constructLeaf(mesh: any): void;
    _constructChildren(mesh: any): void;
    _setAabbSplit(xmin: any, ymin: any, zmin: any, xmax: any, ymax: any, zmax: any): void;
    _setAabbLoose(xmin: any, ymin: any, zmin: any, xmax: any, ymax: any, zmax: any): void;
    collectIntersectRay(vNear: any, eyeDir: any, collectFaces: any, leavesHit: any): any;
    collectIntersectSphere(vert: any, radiusSquared: any, collectFaces: any, leavesHit: any): any;
    addFace(faceId: any, bxmin: any, bymin: any, bzmin: any, bxmax: any, bymax: any, bzmax: any, cx: any, cy: any, cz: any): any;
    _expandAabbLoose(bxmin: any, bymin: any, bzmin: any, bxmax: any, bymax: any, bzmax: any): void;
    pruneIfPossible(): void;
}
export {};
